name: example
description: A sample application demonstrating off_ide.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  hydrated_bloc: ^10.1.1
  off_ide:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
